/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfaz;
import clases_funciones.*;
import edu.uci.ics.jung.algorithms.layout.*;
import edu.uci.ics.jung.graph.*;
import edu.uci.ics.jung.visualization.*;
import edu.uci.ics.jung.visualization.control.*;
import edu.uci.ics.jung.visualization.decorators.*;
import org.apache.commons.collections15.Transformer;
import javax.swing.*;
import java.awt.*;
import java.util.*;
/**
 *
 * @author eduardo
 */
public class BFSDialog extends javax.swing.JDialog {
    grafo datos;
    int n;
    public BFSDialog(grafo data,java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.datos = data;
        this.n = this.datos.proteinas.length;
        initComponents();
        
        int[] compId = new int[n];
        int[] compSize = new int[n];
        for (int i = 0; i < n; i++) compId[i] = -1;

        Cola cola = new Cola(n);
        int nextId = 0;

        for (int i = 0; i < n; i++) {
            if (compId[i] == -1) {
                int id = nextId++;
                compSize[id] = 0;

                cola.encolar(i);
                compId[i] = id;
                compSize[id]++;

                while (!cola.vacia()) {
                    int actual = cola.desencolar();
                    for (int j = 0; j < n; j++) {
                        int peso = 0;
                        if (this.datos.matriz[actual][j] > 0) peso = this.datos.matriz[actual][j];
                        else if (this.datos.matriz[j][actual] > 0) peso = this.datos.matriz[j][actual];

                        if (peso > 0 && compId[j] == -1) {
                            compId[j] = id;
                            compSize[id]++;
                            cola.encolar(j);
                         }
                    }
                }
            }
        }

        int idGrande = 0;
        for (int i = 1; i < nextId; i++) {
            if (compSize[i] > compSize[idGrande]) idGrande = i;
        }

        boolean[] aislado = new boolean[n];
        int cont = 0;
        for (int i = 0; i < n; i++) {
            if (compId[i] != idGrande) {
                aislado[i] = true;
                cont++;
            }
        }

        if (cont == 0) {
            JOptionPane.showMessageDialog(this, "No hay nodos aislados.");
            return;
        }

        Graph<Integer, String> grafo = new UndirectedSparseGraph<>();
        Map<String, Integer> pesosAristas = new HashMap<>();

        for (int i = 0; i < n; i++) {
            if (aislado[i]) grafo.addVertex(i);
        }

        int contAristas = 0;
        for (int i = 0; i < n; i++) {
            if (!aislado[i]) continue;
            for (int j = i+1; j < n; j++) {
                if (!aislado[j]) continue;
                int peso = 0;
                if (this.datos.matriz[i][j] > 0) peso = this.datos.matriz[i][j];
                else if (this.datos.matriz[j][i] > 0) peso = this.datos.matriz[j][i];

                if (peso > 0) {
                    String nombre = "e" + contAristas++;
                    grafo.addEdge(nombre, i, j);
                    pesosAristas.put(nombre, peso);
                }
            }
        }

        FRLayout<Integer, String> layout = new FRLayout<>(grafo);
        layout.setSize(new Dimension(jPanel2.getWidth(), jPanel2.getHeight()));

        VisualizationViewer<Integer, String> vv = new VisualizationViewer<>(layout);
        vv.setPreferredSize(new Dimension(jPanel2.getWidth(), jPanel2.getHeight()));

        vv.getRenderContext().setVertexLabelTransformer(vertex -> this.datos.proteinas[vertex]);
        vv.setGraphMouse(new DefaultModalGraphMouse<>());
        vv.getRenderContext().setEdgeLabelTransformer(edge -> {
            Integer p = pesosAristas.get(edge);
            return p != null ? p.toString() : "";
        });
        jPanel2.setLayout(new BorderLayout());
        jPanel2.add(vv, BorderLayout.CENTER);

        addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                vv.setPreferredSize(new Dimension(jPanel2.getWidth(), jPanel2.getHeight()));
                layout.setSize(new Dimension(jPanel2.getWidth(), jPanel2.getHeight()));
                vv.repaint();
            }
        });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("BioGraph");

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setForeground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 689, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        jButton13.setBackground(new java.awt.Color(255, 153, 153));
        jButton13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton13.setForeground(new java.awt.Color(51, 153, 255));
        jButton13.setText("Volver al Menú Principal");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 802, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        MenuPrincipalFrame volver = new MenuPrincipalFrame(this.datos);
        volver.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton13;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
