/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;
import clases_funciones.*;
import javax.swing.JOptionPane;
/**
 *
 * @author cesardf
 */
public class RutaMasCortaFrame extends javax.swing.JFrame {
    grafo datos;
    /**
     * Creates new form RutaMasCortaFrame
     */
    public RutaMasCortaFrame(grafo data) {
        this.datos = data;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Malgun Gothic", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 255));
        jLabel2.setText("BioGraph");
        jLabel2.setAlignmentX(0.5F);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Proteina Destino");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 102, 255));
        jButton1.setText("Menor resistencia");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 153, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 102, 255));
        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setText("Proteina Origen");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 255, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 102, 255));
        jButton3.setText("Más corta");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(36, 36, 36)))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel2)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField1, jTextField2});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton3});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(21, 21, 21))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextField1, jTextField2});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String origen = jTextField1.getText().trim();
        String destino = jTextField2.getText().trim();
        boolean originario = this.datos.existe(origen);
        boolean destinatario = this.datos.existe(destino);
        if (originario && destinatario ){
            int org = -1, dtn = -1;
            for (int i = 0; i < datos.proteinas.length; i++) {
                if (datos.proteinas[i].equals(origen)) org = i;
                if (datos.proteinas[i].equals(destino)) dtn = i;
            }

            int[] dist = new int[datos.proteinas.length];
            int[] prev = new int[datos.proteinas.length];
            boolean[] visitado = new boolean[datos.proteinas.length];
            for (int i = 0; i < datos.proteinas.length; i++) {
                dist[i] = Integer.MAX_VALUE;
                prev[i] = -1;
            }
            dist[org] = 0;

            for (int x = 0;  x< datos.proteinas.length; x++) {
                int u = -1;
                int minDist = Integer.MAX_VALUE;
                for (int i = 0; i < datos.proteinas.length; i++) {
                    if (!visitado[i] && dist[i] < minDist) {
                        minDist = dist[i];
                        u = i;
                    }
                }
                if (u == -1) break; 
                visitado[u] = true;

                for (int v = 0; v < datos.proteinas.length; v++) {
                    int peso = datos.matriz[u][v];
                    if (peso > 0 && !visitado[v] && dist[u] != Integer.MAX_VALUE) {
                        int nuevaDist = dist[u] + peso;
                        if (nuevaDist < dist[v]) {
                            dist[v] = nuevaDist;
                            prev[v] = u;
                        }
                    }
                }
            }

            if (prev[dtn] == -1 && dtn != org) {
                JOptionPane.showMessageDialog(this, "Es imposible esta interacción");
                return;
            }

            int[] rutaReversa = new int[datos.proteinas.length];
            int largo = 0;
            int actual = dtn;
            while (actual != -1) {
                rutaReversa[largo++] = actual;
                actual = prev[actual];
            }

            if (largo == 1) {
                JOptionPane.showMessageDialog(this, "Has introducido la misma proteina en origen y destino");
                return;
            }

            String[] resultado = new String[2 * (largo - 1)];
            int indice = 0;
            for (int i = largo - 1; i > 0; i--) {
                int desde = rutaReversa[i];       
                int hasta = rutaReversa[i - 1];   
                int peso = datos.matriz[desde][hasta];
                resultado[indice++] = datos.proteinas[hasta]; 
                resultado[indice++] = Integer.toString(peso); 
            }
            String mensaje = resultado[0] + " - " + resultado[1];
            for (int i = 2; i<resultado.length;i +=2){
                mensaje += "," + "\n" + resultado[i] + " - " + resultado[i+1];
            }
            JOptionPane.showMessageDialog(this, mensaje);
        }
        else{JOptionPane.showMessageDialog(this, "La proteina origen o la proteina destino que introduciste no existen");}
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MenuPrincipalFrame volver = new MenuPrincipalFrame(this.datos);
        volver.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String origen = jTextField1.getText().trim();
        String destino = jTextField2.getText().trim();
        boolean originario = this.datos.existe(origen);
        boolean destinatario = this.datos.existe(destino);
        if (originario && destinatario ){    
            int org = -1, dtn = -1;
            for (int i = 0; i < datos.proteinas.length; i++) {
                if (datos.proteinas[i].equals(origen)) org = i;
                if (datos.proteinas[i].equals(destino)) dtn = i;
            }

            int[] prev = new int[datos.proteinas.length];
            int[] dist = new int[datos.proteinas.length];
            for (int i = 0; i < datos.proteinas.length; i++) {
                prev[i] = -1;
                dist[i] = -1;
            }

            Cola cola = new Cola(datos.proteinas.length);
            cola.encolar(org);
            dist[org] = 0;

            while (!cola.vacia()) {
                int u = cola.desencolar();
                if (u == dtn) break; 
                for (int v = 0; v < datos.proteinas.length; v++) {
                    if (datos.matriz[u][v] > 0 && dist[v] == -1) {
                        dist[v] = dist[u] + 1;
                        prev[v] = u;
                        cola.encolar(v);
                    }
                }
            }

            if (dist[dtn] == -1) {
                JOptionPane.showMessageDialog(this, "Es imposible esta interacción");
                return;
            }

            int[] rutaReversa = new int[datos.proteinas.length];
            int largo = 0;
            int actual = dtn;
            while (actual != -1) {
                rutaReversa[largo++] = actual;
                actual = prev[actual];
            }

            if (largo == 1) {
                JOptionPane.showMessageDialog(this, "Has introducido la misma proteina en origen y destino");
                return;
            }

            String[] resultado = new String[2 * (largo - 1)];
            int indice = 0;
            for (int i = largo - 1; i > 0; i--) {
                int desde = rutaReversa[i];
                int hasta = rutaReversa[i - 1];
                int peso = datos.matriz[desde][hasta];
                resultado[indice++] = datos.proteinas[hasta];
                resultado[indice++] = Integer.toString(peso);
            }
            String mensaje = resultado[0] + " - " + resultado[1];
            for (int i = 2; i<resultado.length;i +=2){
                mensaje += "," + "\n" + resultado[i] + " - " + resultado[i+1];
            }
            JOptionPane.showMessageDialog(this, mensaje);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
